### ISSUE TITLE
Linux app

### ISSUE THREAD

**Issue by xmha97** [boredcodebyk/mintcalc#1]
Hi, thanks for this app.
Please publish Linux version.
Flutter is a cross-platform framework.

**Comment by boredcodebyk** [comment]
good idea. I'll, if possible, release linux version in next version. do u want like AppImage or in store like Snap and Flatpak?

**Comment by xmha97** [comment]
> good idea. I'll, if possible, release linux version in next version. do u want like AppImage or in store like Snap and Flatpak?

All Linux repositories are blocked in my country!
Snap, Flatpak, apt, apt-get and etc.
We have to use Linux offline. 😂
So we need a deb package or AppImage file.
Thanks 🙏

**Comment by boredcodebyk** [comment]
i'm closing this for now, and it will be implemented in future after writing everything from scratch and optimizing

**Comment by xmha97** [comment]
Ok 👍
