### ISSUE TITLE
Improve landscape

### ISSUE THREAD

**Issue by xmha97** [boredcodebyk/mintcalc#2]
Please improve the landscape mode:

![Screenshot_2023-07-13-18-01-09-225_bored codebyk mintcalc](https://github.com/boredcodebyk/mintcalc/assets/23485114/05f9d0b5-6705-4ea1-a6b2-678ac20d3e7b)

**Comment by boredcodebyk** [comment]
the next version aims to optimize for larger displays and that also include the landscape mode along with other bug fixes

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by boredcodebyk** [comment]
fixed in https://github.com/boredcodebyk/mintcalc/commit/00fdce31dc440cba9a64539528f0fc283905195e
