### ISSUE TITLE
Version mismatch between F-Droid and the app

### ISSUE THREAD

**Issue by onchov** [boredcodebyk/mintcalc#27]
As per the subject, different version info is shown on Mintcalc's F-Droid page and on the info page within the app.

F-Droid:
![signal-2024-10-07-212939_002](https://github.com/user-attachments/assets/992a314e-5702-4d8d-a778-03adbdb837cb)

App (Settings > About):
![signal-2024-10-07-212939_003](https://github.com/user-attachments/assets/d1081040-a8ff-47f3-9be8-1afc4ab7c702)

**Comment by boredcodebyk** [comment]
That mistakes on me. I coded it long back so the inapp version is written as string manually
