### ISSUE TITLE
Bug in the display for long calculation

### ISSUE THREAD

**Issue by Toine51** [boredcodebyk/mintcalc#3]
![Screenshot_20230723-192524_Mint Calculator.png](https://github.com/boredcodebyk/mintcalc/assets/134766617/0bba66f0-1125-451b-adff-59001c4282c0)

My calculation is : 3+3+3+3+3+3+3+3+3+3+1

We don't see the end of the calculation because it does'nt move dynamically as we type.

**Comment by boredcodebyk** [comment]
no worries, im working on a fix along with other bug fixes + trying to optimize the code. should be available next week if everything goes right (im very much new to flutter actually hehe) (along will have windows and linux versions too probably, not sure tho)

**Comment by Toine51** [comment]
Alright thanks ! And no worries :)

**Comment by Toine51** [comment]
Hey !
No rush AT ALL haha but when do you expect the release of the new version ? 😊

**Comment by boredcodebyk** [comment]
ran into little problem solving but should be alright, currently optimizing

**Comment by boredcodebyk** [comment]
fixed in https://github.com/boredcodebyk/mintcalc/commit/00fdce31dc440cba9a64539528f0fc283905195e with limitation. im planning to write from scratch and remove unwanted codes or codes which maybe be important
