### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by fillwithjoy1** [boredcodebyk/mintcalc#4]
Just wanted to say, nice app! I look forward to it being improved
One of the suggestions I have is to implement haptic feedback on each tap. It feels more satisfying this way.

**Comment by boredcodebyk** [comment]
noted :D

**Comment by fillwithjoy1** [comment]
> noted :D

I've come from Google calculator and found out that they use the INTERNET permission... very cool google. anyways, found this but it lacks some features :(

**Comment by fillwithjoy1** [comment]
> enabled haptic feedback in [00fdce3](https://github.com/boredcodebyk/mintcalc/commit/00fdce31dc440cba9a64539528f0fc283905195e) but idk why it doesn't work

did a quick skim over the code, seems like it doesn't exist

**Comment by fillwithjoy1** [comment]
Made a pull request in #7 that adds it, but still tweaking some values around

**Comment by boredcodebyk** [comment]
added in https://github.com/boredcodebyk/mintcalc/commit/2559a8bb8e1a444e267343b86e47d8033a139e02 with your help, thank you for your contribution

**Comment by fillwithjoy1** [comment]
> added in [2559a8b](https://github.com/boredcodebyk/mintcalc/commit/2559a8bb8e1a444e267343b86e47d8033a139e02) with your help, thank you for your contribution

used chatgpt because i had no idea how to use flutter :P 
looks similar to javascript though
